name: Cypress Tests
on:
  push:
    branches: [ main ]
jobs:
  cypress-tests:
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v3
       - uses: actions/setup-node@v2
         with:
            node-version: '14'
       - name: Install Dependencies
         run: npm install
       - name: Install Cypress
         run: npm install cypress
       - name: Install Cypress
         run: npm run cy:run:chrome
