name: Cypress Tests
on:
  push:
    branches: [ main ]
jobs:
  cypresstests:
    runs-on: ubuntu-latest
    # container:
    #   image: mcr.microsoft.com/playwright:v1.29.1-focal
    #   env:
    #     ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run tests
        run: |
          echo "Start the shopping store application"
          ./shopping-store-linux-amd64 &
        #   npm ci
        #   echo "Run cypress tests"
        #   npm run test:ci